### ISSUE TITLE
nvidia card not working inside container

### ISSUE THREAD

**Issue by tulku** [Ekumen-OS/Noah-bot-simulation-ros2#20]
When trying to run the simulation on a new Ubuntu 22.04 installation on a new laptop, the GL windows were not working, meaning that both rviz and gazebo showed the UI, but the 3d scene in both applications is just black.

Trying to run `glmark2` inside the container also failed, and stated that the Mesa drivers are being used.

**Comment by gonzodepedro** [comment]
This is now working for me
